name: CI
on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.repository == 'codeably-io/jest-ai'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: true

      - name: Run test script
        run: npm test

      - name: Run build script
        run: npm run build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
